unique_ids:
  assets:
    standard-page.html: NZBJCDW7TRN7ZETI5VXWA3MQYKVRCACQ
    theme.css: TL3U4U2V2TZLCWYS3ISXH7AR4KVDXS2B
  forms:
    Form1: 4JBDXIGS6GSEWF37WK37PJIXCWAWY755
  modules: {}
  scripts: {}
  server_modules: {}
